--
image: atlassian/default-image:latest
pipelines:
  branches:
    master:
      - step:
          script:
            - ssh -i ubuntu@13.233.183.105 'cd /home/ubuntu/faaz ; git pull origin master ; echo "Changes deployed successfully"'

    dev:
      - step:
          script:
            - ssh -i ubuntu@13.233.183.105 'cd /home/ubuntu ; git pull origin dev ; echo "Changes deployed successfully"'
